// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuOru0yvXF_6f8m1zQrkjSwdRmxN3Zi3k',
    appId: '1:762986913098:web:7bbc4191d3092ef4d075b3',
    messagingSenderId: '762986913098',
    projectId: 'ifa-21312052',
    authDomain: 'ifa-21312052.firebaseapp.com',
    storageBucket: 'ifa-21312052.appspot.com',
    measurementId: 'G-DJJR6VMC51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0JuHsT-xg03HzAr2NXh-NGaExHKrjAk',
    appId: '1:762986913098:android:76bd66f94f534f94d075b3',
    messagingSenderId: '762986913098',
    projectId: 'ifa-21312052',
    storageBucket: 'ifa-21312052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYeCc6uUIkboY3g630pVOIUuVHfJgC0E',
    appId: '1:762986913098:ios:8ccba134e9fa9537d075b3',
    messagingSenderId: '762986913098',
    projectId: 'ifa-21312052',
    storageBucket: 'ifa-21312052.appspot.com',
    iosBundleId: 'com.example.ifa21312097',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYeCc6uUIkboY3g630pVOIUuVHfJgC0E',
    appId: '1:762986913098:ios:33f7b421720c14ddd075b3',
    messagingSenderId: '762986913098',
    projectId: 'ifa-21312052',
    storageBucket: 'ifa-21312052.appspot.com',
    iosBundleId: 'com.example.ifa21312097.RunnerTests',
  );
}
